#!/usr/bin/env python3
"""Converts the iOS String Catalog into Android string resources (docs/PLAN.md AND-M6-01).

Reads ../insiteview-ios/Resources/Localizable.xcstrings (or the path given) and writes
features/src/main/res/values{,-b+pt+BR,-es}/strings.xml. Each resource name is derived from the
English key; the key and the translator comment are kept in an XML comment above each entry, so a
screen ported from Swift finds its string by searching for the English text.

- `%@` becomes `%s`, `%lld` becomes `%d`, and they're numbered (`%1$s`) when there are several.
- Apple's inflection markup (`^[%lld day](inflect: true)`) becomes a <plurals> with one/other.
- A missing translation falls back to the English text.

Android-only strings live in values*/strings_android.xml, which this script never touches.
Usage: scripts/xcstrings-to-android.py [path/to/Localizable.xcstrings]
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "..", "insiteview-ios", "Resources", "Localizable.xcstrings")
RES = os.path.join(ROOT, "features", "src", "main", "res")
LOCALES = {"en": "values", "pt-BR": "values-b+pt+BR", "es": "values-es"}

INFLECT = re.compile(r"\^\[(%lld) ([^\]]+)\]\(inflect: true\)")
# Resource names become Java fields, so they can't be keywords.
JAVA_KEYWORDS = set("""abstract assert boolean break byte case catch char class const continue default do
double else enum extends final finally float for goto if implements import instanceof int interface long
native new package private protected public return short static strictfp super switch synchronized this
throw throws transient try void volatile while true false null""".split())
PLACEHOLDER = re.compile(r"%(@|lld|%)")

# Plural forms of the inflected words in the catalog (English, Portuguese, Spanish).
PLURALS = {
    "minute": "minutes", "day": "days", "try": "tries", "document": "documents", "item": "items",
    "minuto": "minutos", "dia": "dias", "tentativa": "tentativas", "documento": "documentos",
    "día": "días", "intento": "intentos", "elemento": "elementos",
}


def plural_of(word, locale):
    if locale == "pt-BR" and word == "item":
        return "itens"
    return PLURALS.get(word, word + "s")


def resource_name(key, used):
    name = re.sub(r"\^\[%lld ([^\]]+)\]\(inflect: true\)", r"n \1", key)
    name = name.replace("%@", "x").replace("%lld", "n").replace("%%", "percent")
    name = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")[:60].rstrip("_") or "string"
    if name[0].isdigit():
        name = "s_" + name
    if name in JAVA_KEYWORDS:
        name += "_action"
    base, n = name, 2
    while name in used:
        name = f"{base}_{n}"
        n += 1
    used.add(name)
    return name


def escape(text):
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = text.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n")
    if text.startswith("@") or text.startswith("?"):
        text = "\\" + text
    return text


def android_format(text):
    """%@ → %s, %lld → %d, numbered when there's more than one; %% stays."""
    count = len([m for m in PLACEHOLDER.finditer(text) if m.group(1) != "%"])
    index = 0

    def repl(m):
        nonlocal index
        if m.group(1) == "%":
            return "%%"
        index += 1
        kind = "s" if m.group(1) == "@" else "d"
        return f"%{index}${kind}" if count > 1 else f"%{kind}"

    return PLACEHOLDER.sub(repl, text)


def comment(text):
    return text.replace("--", "- -")


def main():
    catalog = json.load(open(SOURCE, encoding="utf-8"))
    strings = catalog["strings"]
    used = set()
    names = {key: resource_name(key, used) for key in sorted(strings, key=str.lower)}
    for locale, folder in LOCALES.items():
        lines = [
            '<?xml version="1.0" encoding="utf-8"?>',
            "<!-- Generated by scripts/xcstrings-to-android.py from insiteview-ios Localizable.xcstrings. Don't edit. -->",
            '<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="UnusedResources,MissingTranslation,PluralsCandidate,Typos">',
        ]
        for key in sorted(strings, key=str.lower):
            entry = strings[key]
            value = key
            unit = entry.get("localizations", {}).get(locale, {}).get("stringUnit")
            if locale != "en" and unit and unit.get("value"):
                value = unit["value"]
            note = entry.get("comment", "")
            lines.append(f"    <!-- {comment(key)}{' · ' + comment(note) if note else ''} -->")
            name = names[key]
            match = INFLECT.search(value)
            if match:
                word = match.group(2)
                one = android_format(INFLECT.sub(lambda m: f"%lld {word}", value))
                other = android_format(INFLECT.sub(lambda m: f"%lld {plural_of(word, locale)}", value))
                lines.append(f'    <plurals name="{name}">')
                lines.append(f'        <item quantity="one">{escape(one)}</item>')
                if locale != "en":
                    lines.append(f'        <item quantity="many">{escape(other)}</item>')
                lines.append(f'        <item quantity="other">{escape(other)}</item>')
                lines.append("    </plurals>")
            else:
                formatted = android_format(value)
                attr = ' formatted="false"' if "%" in formatted and not PLACEHOLDER.search(value) else ""
                lines.append(f'    <string name="{name}"{attr}>{escape(formatted)}</string>')
        lines.append("</resources>")
        os.makedirs(os.path.join(RES, folder), exist_ok=True)
        with open(os.path.join(RES, folder, "strings.xml"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(strings)} strings to {', '.join(LOCALES.values())}")


if __name__ == "__main__":
    main()
